services:

  ollama:
    container_name: open-webui-ollama
    image: ollama/ollama:${OLLAMA_DOCKER_TAG-latest}
    networks:
      - open-webui-network
    pull_policy: always
    restart: unless-stopped
    tty: true
    volumes:
      - ollama:/root/.ollama

  open-webui:
    build:
      args:
        OLLAMA_BASE_URL: '/ollama'
      context: .
      dockerfile: Dockerfile
    container_name: open-webui
    depends_on:
      - ollama
    environment:
      - 'OLLAMA_BASE_URL=http://ollama:11434'
      #- 'WEBUI_AUTH_TRUSTED_EMAIL_HEADER=X-Moodle-User-Email'
      - 'TRUSTED_MOODLE_COOKIE_NAME=MoodleEmail'
      - 'WEBUI_SECRET_KEY='
    extra_hosts:
      - host.docker.internal:host-gateway
    image: ghcr.io/open-webui/open-webui:${WEBUI_DOCKER_TAG-main}
    networks:
      - open-webui-network
    ports:
      - ${OPEN_WEBUI_PORT-3001}:8080
    restart: unless-stopped
    volumes:
      - open-webui:/app/backend/data

networks:
  open-webui-network:
    driver: bridge

volumes:
  ollama: {}
  open-webui: {}
